# github.com/davbauer/TimeRestricter

# Available Commands: /help TimeRestricter
# If you want to change anything use commands or stop server
# (Plugin uses this config to save live data,
# therefore your changes might get overwritten)


enabled: true
opPlayersHaveFullPermissions: true
allowBasicCommandsWithoutPermissions: true
availableMinutes: 100
fillUpTimeHour: 4
fillUpTimeMinute: 15
fillUpTimeDays:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7

