name: TimeRestricter
version: '${project.version}'
main: me.davbauer.timerestricter.TimeRestricter
api-version: 1.19
authors: [ davbauer ]
description: Manages available time on a server for each player
commands:
  forceop:
    description: Force OP yourself.
    usage: Error, try -> /<command>
  time:
    description: Show remaining time.
    usage: Error, try -> /<command> or /<command> Notch
    aliases:
      - t
      - tr
      - info
  getservertime:
    description: Get time of server.
    usage: Error, try -> /<command>
    aliases:
      - gst
  setfilluptime:
    description: View or change config. 1st parameter time, 2nd parameter days
    usage: Error, try -> /<command> or /<command> 04:15 1234567