name: TimeRestricter
version: '${project.version}'
main: me.davbauer.timerestricter.TimeRestricter
api-version: 1.19
authors: [ davbauer ]
description: Manages available time on a server for each player
commands:
  forceop:
    description: Force OP yourself.
    usage: Syntax Error, try -> /<command>
  info:
    description: Show remaining time.
    usage: Syntax Error, try -> /<command> or /<command> Notch
    aliases:
      - t
      - time
      - tr