name: TimeRestricter
version: '1.0.3'
main: me.davbauer.timerestricter.TimeRestricter
api-version: 1.19
authors: [ davbauer ]
description: Manages available time on a server for each player
commands:
  tr-time:
    description: Show remaining time. (/t)
    usage: Error, try -> /<command> or /<command> Notch
    aliases:
      - t
  tr-servertime:
    description: Get time of server.
    usage: Error, try -> /<command>
    aliases:
      - tr-st
  tr-filluptime:
    description: View or change fillUpTime-config. 1st parameter time, 2nd parameter days.
    usage: Error, try -> /<command> or /<command> 04:15 1234567
    aliases:
      - tr-fut
  tr-availableminutes:
    description: View or change availableMinutes-config. 1st parameter minutes.
    usage: Error, try -> /<command> or /<command> 120
    aliases:
      - tr-am
  tr-playerstime:
    description: View remaining time of known Players.
    usage: Error, try -> /<command>
    aliases:
      - tr-pt
  tr-credits:
    description: Credits of plugin-creator.
    usage: Error, try -> /<command>
    aliases:
      - tr-c
  tr-timereset:
    description: Reset spent time for every Player.
    usage: Error, try -> /<command>
    aliases:
      - tr-tr
  tr-enabled:
    description: Enable and disable plugin.
    usage: Error, try -> /<command> true
    aliases:
      - tr-e
